# Generated by Django 5.1.4 on 2025-08-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
