# Generated by Django 5.1.4 on 2025-08-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='bio',
            field=models.TextField(blank=True, default="Hi there! I'm a creator. Your support helps me do what I love!", help_text='Your Bio help your followers know more about you'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='This is where your UPI ID goes', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('qr_generations', models.PositiveIntegerField(default=0)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
